# Generated by Django 4.1.2 on 2022-11-11 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='address',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='password',
        ),
    ]
